### ISSUE TITLE
有新需求在这描述

### ISSUE THREAD

**Issue by wangsrGit119** [wangsrGit119/mini-blog-halo#1]
**有什么新的功能在这儿可以描述出来**

**Comment by Passto-go** [comment]
小程序里面无法打开视频，不知道是配置问题还是啥，辛苦大佬帮忙确认下。手机：iPhone12 PRO，最新系统。
![Uploading 微信图片_20210401204506.png…]()

**Comment by wangsrGit119** [comment]
@PandaQ1 我这边试了视频是没问题的，截图请看
![](https://cdn.jsdelivr.net/gh/wangsrGit119/wangsr-image-bucket/img-article/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20210402105308.jpg)

- 视频markdown写法

```
<video class="video" controls="true" src="https://www.wangsrbus.cn/wangsr-font/bandicam_2021-04-02_10-10-01-334.mp4">视频</video>
```

**Comment by Passto-go** [comment]
@wangsrGit119 已定位问题，是markdown视频语法不同导致。感谢大佬～

**Comment by wangsrGit119** [comment]
> @wangsrGit119 已定位问题，是markdown视频语法不同导致。感谢大佬～

木事 解决就好

**Comment by samtto** [comment]
我是用相对路径的，在小程序中图片均无法显示。

**Comment by wangsrGit119** [comment]
> 我是用相对路径的，在小程序中图片均无法显示。

需要用绝对路径呢，halo后台发布的时候是绝对路径，展示资源，小程序不储存文件，所以相对路径是找不到的，bbs论坛回复你了
[https://bbs.halo.run/d/1383-mini-blog-halohaloapi/31](https://bbs.halo.run/d/1383-mini-blog-halohaloapi/31)

**Comment by Sh1ft8** [comment]
是否考虑增加一个文章分享生成分享海报的功能。

**Comment by wangsrGit119** [comment]
> 是否考虑增加一个文章分享生成分享海报的功能。

@Lekou520 嗯呢，下一个版本会加，同时也会优化第三个主页页面，增加个人日志展示功能

**Comment by yuyanghf** [comment]
你好，留言板功能能否开源，谢谢！

**Comment by wangsrGit119** [comment]
> 你好，留言板功能能否开源，谢谢！

已开源

**Comment by yuyanghf** [comment]
谢谢！之前已联系过您，收到了源代码，谢谢您！




YUYANG
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangsrGit119/mini-blog-halo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月17日(星期五) 下午5:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangsrGit119/mini-blog-halo] 有新需求在这描述 (#1)





  
你好，留言板功能能否开源，谢谢！
  
已开源
