### ISSUE TITLE
最新版本：登录后台一直显示非管理员，无法登录！评论、收藏、文章功能正常

### ISSUE THREAD

**Issue by Yohmien** [wangsrGit119/mini-blog-halo#10]
配置如下：
![image](https://user-images.githubusercontent.com/77838031/159173876-64f5eff7-796e-4633-b064-e9ac34a5789f.png)
![image](https://user-images.githubusercontent.com/77838031/159173605-2594eb1e-117d-479a-b9af-7e4a973aad48.png)
报错如下：
![image](https://user-images.githubusercontent.com/77838031/159173888-9f5cefd4-ea1d-41c9-849a-4a20d1206a32.png)
![image](https://user-images.githubusercontent.com/77838031/159173639-cd5d01b3-6eda-41db-8e2d-68d695053ca5.png)
可能原因如下：
![image](https://user-images.githubusercontent.com/77838031/159173704-e3780190-885f-426c-9737-ff21cae172af.png)
求大佬帮忙！！！

**Comment by wangsrGit119** [comment]
openID应该没有配置对,在开发模拟器上点击头像，然后控制台会输出一个opneID，填在配置里面

**Comment by Yohmien** [comment]
| |
林海淋
|
|
***@***.***
|
解决了！谢谢大佬
在2022年3月21日 ***@***.***> 写道：

openID应该没有配置对,在开发模拟器上点击头像，然后控制台会输出一个opneID，填在配置里面

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
