### ISSUE TITLE
登录后台调用云函数貌似无法获取环境变量值

### ISSUE THREAD

**Issue by zhangbaiquan** [wangsrGit119/mini-blog-halo#12]
大佬你好，非常感谢你的项目，我在部署的时候遇到云函数貌似无法获取变量值的问题，登录后台页面均无法验证成功，还没有发现是什么原因，我对前端及小程序开发不甚了解，可能是我使用不当，如您可提供指导，非常感谢。

<img width="2349" alt="Snipaste_2022-07-28_23-20-12" src="https://user-images.githubusercontent.com/22684684/181576196-a6eb17c6-d7a4-481b-bc2f-adde9145c450.png">

在云函数中debug 我这里看起来是没有获取到openId_me，username_halo，pwd_halo 这些变量的值

<img width="1718" alt="image" src="https://user-images.githubusercontent.com/22684684/181578265-6f3e24cd-1f8e-4e00-998b-83e0a9de1c39.png">

<img width="1718" alt="image" src="https://user-images.githubusercontent.com/22684684/181577626-9c4b1295-591e-4b8a-9d84-d4cd52e0ac63.png">

**Comment by wangsrGit119** [comment]
文档上加下我微信，我抽空远程看下

**Comment by wangsrGit119** [comment]
对了，最新版的小程序我还没上传的哦git，你加我后我发你包
