### ISSUE TITLE
使用反馈

### ISSUE THREAD

**Issue by samtto** [wangsrGit119/mini-blog-halo#2]
感谢分享
我是小白，不会做程序，只是拿来写日记呢
使用过程中如下问题：
1、后台设置的的相对路径，在小程序中无法加载图片，通过修改一文章，把图片路径修改为绝对路径的话，可以正常显示，报错如下：
```
[渲染层网络层错误] Failed to load local image resource /upload/2021/03/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20210318224822-tuya-20a07dc9625e4f18a965890e7367ef1c.jpg 
 the server responded with a status of 500 (HTTP/1.1 500 Internal Server Error) 
```
2.评论功能写了邮件和内容后，点击保存无响应，如果没有评论的文章，后面的显示建议就不显示而不是灰色的空白。
3.分类页中有加密的分类也会加载出来，还好内容不会加载出来，建议隐藏加密分类；
4.分类页中，如果一直下拉，建议把分类置顶，分类选择项不随分类而上飘，更美观；
5.在“我的”内容页，日记不需要体现，因为用户看不到，并且对该页面做个美化，再不行，底下内容还不如放个图片；
6.在H5和电脑端都可以通过如下代码实现视频的播放功能，但在小程序中不显示，有没有更好的建议？
7.请教下文章详情页中顶部图到哪修改？
```
<div style="position: relative; padding: 30% 45%;">
<iframe style="position: absolute; width: 100%; height: 100%; left: 0; top: 0;"src="https://ABC.COM/6ac3a47bvodcq1303030555/9606e56d5285890815461825515/bAaxrwyxCQkA.mp4" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true" sandbox="allow-top-navigation allow-same-origin allow-forms allow-scripts"></iframe>
</div>
```

**Comment by wangsrGit119** [comment]
@samtto 
@samtto#8230 

- 1.图片路径

> 图片必须是绝对路径因为这个在web端同样需要，数据库里面存放的就是绝对路径（`通过halo后台发布的文章都带`），小程序内部无法使用相对路径，因为你的这些文件小程序内部不储存

- 2.评论

>评论保存无响应是不是因为你的`云函数没有上传`，有个云函数`非法内容校验`的，否则微信`审核是通不过`的，然后评论为空是用的骨架屏是为了好看一点，你仔细观察的话会有动态变化。

- 3.加密这个我确实忽略了，后面新版本我会加上

- 4.分类置顶这个建议也可以，get
- 5.我的内容这个作为后期扩展项的，打算开放日志撰写入口的，小功能块多了的话就会美观一点，现在是空荡荡的
- 6.视频播放(直接用video标签即可，测试过均属正常，无论web端还是小程序端，web端你觉得需要调样式，直接在style里面写css即可)

```
<video class="video" controls="true" src="https://www.wangsrbus.cn/wangsr-font/bandicam_2021-04-02_10-10-01-334.mp4">视频</video>
```
7.文章详情页顶部图在article,wxml的页面布局
```
<l-capsule-bar 
bind:linlefttap="onClickLeft"
home-page="/pages/index/index"
capsule-color="white" 
bg-color="transparent">
  <image class="capsule-bar-bg" style="height:{{capsuleBarHeight+100}}rpx;" src="http://cdn.jsdelivr.net/gh/wangsrGit119/wangsr-image-bucket/img-article/photo-1507738978512-35798112892c.jfif" />
</l-capsule-bar>
```

- 8.怎么说呢，之前的简洁一点但是功能也就相对少一点，所以我尽可能的避免繁琐的内容展现，首页文章展示基本参考的微信读书，其实去年就已经有这个了，但是后台是我自己的用的`springboot+dubbo`,很多人下载后服务都启动不了，比较不友好，换成优秀的halo大家更方便呢。

**Comment by qiulongwen** [comment]
提交审核不通过怎么办，说是评论里面，有用户自行生成的内容，属于社交范畴
