### ISSUE TITLE
小程序使用征集

### ISSUE THREAD

**Issue by wangsrGit119** [wangsrGit119/mini-blog-halo#3]
有在使用的可以放到下面，格式
> 名称：苏克分享
> 小程序码：![苏克分享](https://cdn.jsdelivr.net/gh/wangsrGit119/wangsr-image-bucket/img-article/blog-wxchat-gh_0b089e4e80ed_258.jpg)
> 个人网站：[https://wangsrbus.cn](https://wangsrbus.cn)

**Comment by Sh1ft8** [comment]
跟一个，使用了默认字体，去掉了图片模糊，分类标题改成了name值
![image](https://user-images.githubusercontent.com/76936213/113655684-e4242180-96cc-11eb-991a-18fa2ddaed0e.png)
个人网站：https://g0d.cn

**Comment by wangsrGit119** [comment]
> 跟一个，使用了默认字体，去掉了图片模糊，分类标题改成了name值
> ![image](https://user-images.githubusercontent.com/76936213/113655684-e4242180-96cc-11eb-991a-18fa2ddaed0e.png)
> 个人网站：https://g0d.cn

看了下你的小程序端没法评论，感觉云函数应该没上传，本地控制开看下有啥错误，对了新版本预计周末发布，界面比现在更加舒服，增加海报功能

**Comment by samtto** [comment]
小程序已经上线啦  
![gh_da3c0dc9a11f_258](https://t.tmtd.cn/upload/2021/04/gh_da3c0dc9a11f_258-3f688e9cd5a847bfac0a3d2d7d13284b.jpg)
个人网站：https://t.tmd.cn

**Comment by wangsrGit119** [comment]
@Lekou520  @samtto 小程序版本已经发生大的变化，用的博主看到的话可以换下新版本
