### ISSUE TITLE
Tabbar遮挡了最后一条数据，评论时间显示NaN

### ISSUE THREAD

**Issue by curlsongu** [wangsrGit119/mini-blog-halo#5]
### 1. 滚动条已经到最底部了，但是列表中的最后一条消息被遮挡住了。
![image](https://user-images.githubusercontent.com/42939916/114256337-3d50c580-99eb-11eb-8353-c1a187a08f4a.png)

### 2. 评论中的‘“xx天前“”显示异常
![image](https://user-images.githubusercontent.com/42939916/114256409-a6d0d400-99eb-11eb-9639-c43a8ecabde3.png)

**Comment by wangsrGit119** [comment]
嗯呢，新版本优化了些，你下载主分支或者1.10分支的看下有啥问题没

**Comment by wangsrGit119** [comment]
@curlsongu 新版本的改动比较大，你先下载下来看看，有啥问题没
