### ISSUE TITLE
第二版本使用反馈

### ISSUE THREAD

**Issue by samtto** [wangsrGit119/mini-blog-halo#6]
1.生成二维码和评价的功能叠一起了；
![生成二维码和评价的功能倒一起了](https://images.gitee.com/uploads/images/2021/0410/173921_f51ba445_1443944.png "2021-04-10_173839.png")
2.加密的分类，会显出来，建议删除加密分类；
![加密的分类，会显出来](https://images.gitee.com/uploads/images/2021/0410/174106_ecb27749_1443944.png "2021-04-10_174009.png")
3.首页建议由置顶贴+新贴组成；
4.建议分类不会随着用户下拉而上升；
5.建议说明里增加个msgcheck使用方法；

此次UI修改非常美丽！感谢大神！

**Comment by wangsrGit119** [comment]
@samtto get!
