### ISSUE TITLE
baseUrl：基础的API（halo博客的）

### ISSUE THREAD

**Issue by little-2pig** [wangsrGit119/mini-blog-halo#8]
baseUrl：基础的API（halo博客的）是在哪里找不到，不是api就可以了吗

**Comment by little-2pig** [comment]
配置好绝对路径后还是会报错
[渲染层网络层错误] Failed to load local image resource XXXX

**Comment by wangsrGit119** [comment]
> baseUrl：基础的API（halo博客的）是在哪里找不到，不是api就可以了吗

登录Halo后台，博客设置，右上角切换到高级设置，然后里面有个API设置，打开API设置；选择右边其他设置，打开全局绝对路径
